"""
Additive migration for the Pro Content Hub + Mock-Paper marketplace.

Idempotent: safe to run repeatedly. Adds the new content/marketplace tables,
an is_admin flag on users, and marks user id 1 as admin.

    set DATABASE_URL=postgresql://...neon.tech/...
    python migrate_add_content.py
"""
import os
import sys
import psycopg

STATEMENTS = [
    """CREATE TABLE IF NOT EXISTS resources (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category    TEXT NOT NULL,
        title       TEXT NOT NULL,
        url         TEXT NOT NULL,
        description TEXT,
        created_at  TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
    )""",
    """CREATE TABLE IF NOT EXISTS pro_posts (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind        TEXT NOT NULL,              -- 'tip' | 'note'
        subject     TEXT,
        title       TEXT NOT NULL,
        body        TEXT NOT NULL,
        period      TEXT,                       -- e.g. 'June 2026' for monthly notes
        created_at  TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
    )""",
    """CREATE TABLE IF NOT EXISTS mock_papers (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title       TEXT NOT NULL,
        subject     TEXT,
        board       TEXT,
        description TEXT,
        price_pence INTEGER NOT NULL DEFAULT 100,
        filename    TEXT,                       -- stored file on the Railway volume
        orig_name   TEXT,
        created_at  TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
    )""",
    """CREATE TABLE IF NOT EXISTS purchases (
        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        mock_paper_id     INTEGER NOT NULL REFERENCES mock_papers(id) ON DELETE CASCADE,
        stripe_session_id TEXT,
        purchased_at      TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
        UNIQUE (user_id, mock_paper_id)
    )""",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0",
    "UPDATE users SET is_admin = 1 WHERE id = 1",
]

url = os.environ.get("DATABASE_URL")
if not url:
    sys.exit("DATABASE_URL not set")

con = psycopg.connect(url)
with con.cursor() as cur:
    for stmt in STATEMENTS:
        cur.execute(stmt)
con.commit()

with con.cursor() as cur:
    for t in ["resources", "pro_posts", "mock_papers", "purchases"]:
        cur.execute("SELECT count(*) FROM " + t)
        print("  %-12s ok (rows=%d)" % (t, cur.fetchone()[0]))
    cur.execute("SELECT id, email, is_admin FROM users ORDER BY id")
    print("  users:", cur.fetchall())
con.close()
print("Content/marketplace migration applied.")
