"""
Scan app.py (or any .py) for SQLite-only patterns that Postgres will reject.

The db.py shim handles `?` placeholders and lastrowid for you. Everything
this script reports needs a human edit.

Usage:
    python scan_sqliteisms.py app.py
    python scan_sqliteisms.py .            # whole project
"""

from __future__ import annotations

import os
import re
import sys

CHECKS = [
    (
        r"\bimport\s+sqlite3\b|\bsqlite3\.",
        "sqlite3 import/usage",
        "Replace with `from db import get_db`. Delete the sqlite3 import.",
    ),
    (
        r"INSERT\s+OR\s+IGNORE",
        "INSERT OR IGNORE",
        "Postgres: `INSERT ... ON CONFLICT DO NOTHING`.",
    ),
    (
        r"INSERT\s+OR\s+REPLACE",
        "INSERT OR REPLACE",
        "Postgres: `INSERT ... ON CONFLICT (col) DO UPDATE SET ...`.",
    ),
    (
        r"\bAUTOINCREMENT\b",
        "AUTOINCREMENT",
        "Postgres: `GENERATED BY DEFAULT AS IDENTITY`. Usually only in init_db().",
    ),
    (
        r"\bIFNULL\s*\(",
        "IFNULL()",
        "Postgres: `COALESCE(...)`. Works in both, so just switch.",
    ),
    (
        r"\bGROUP_CONCAT\s*\(",
        "GROUP_CONCAT()",
        "Postgres: `STRING_AGG(col, ',')`.",
    ),
    (
        r"datetime\s*\(\s*['\"]now['\"]",
        "datetime('now')",
        "Postgres: `NOW()` or `CURRENT_TIMESTAMP`.",
    ),
    (
        r"\bstrftime\s*\(",
        "strftime()",
        "Postgres: `TO_CHAR(col, 'YYYY-MM-DD')` or `DATE_TRUNC(...)`.",
    ),
    (
        r"\bjulianday\s*\(",
        "julianday()",
        "Postgres: subtract timestamps directly, or EXTRACT(EPOCH FROM ...).",
    ),
    (
        r"\bLIKE\b",
        "LIKE",
        "SQLite's LIKE is case-INsensitive for ASCII; Postgres' is case-SENSITIVE. "
        "Use ILIKE if you relied on that (search boxes, topic filters).",
    ),
    (
        r"\|\|",
        "|| concatenation",
        "Fine in Postgres — but NULL || 'x' is NULL. Wrap in COALESCE if needed.",
    ),
    (
        r"\bPRAGMA\b",
        "PRAGMA",
        "No Postgres equivalent. Usually safe to delete.",
    ),
    (
        r"\.executescript\s*\(",
        "executescript()",
        "db.py provides a shim, but check the script has no SQLite-only DDL.",
    ),
    (
        r"row_factory",
        "row_factory assignment",
        "db.py sets this for you. Remove the manual assignment.",
    ),
    (
        r"\bLIMIT\s+\d+\s*,\s*\d+",
        "LIMIT x, y",
        "Postgres: `LIMIT y OFFSET x`.",
    ),
    (
        r"\bcheck_same_thread\b",
        "check_same_thread",
        "sqlite3-only connect kwarg. Delete it.",
    ),
    (
        r"\bORDER\s+BY\s+RANDOM\s*\(\s*\)",
        "RANDOM()",
        "Postgres also has RANDOM() — fine, no change needed.",
    ),
]

SKIP_DIRS = {".git", "__pycache__", "venv", ".venv", "node_modules", "migrations"}


def scan_file(path):
    hits = []
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()
    except OSError:
        return hits
    for n, line in enumerate(lines, 1):
        for pattern, label, advice in CHECKS:
            if re.search(pattern, line, re.IGNORECASE):
                hits.append((n, label, advice, line.rstrip()))
    return hits


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else "app.py"
    files = []
    if os.path.isdir(target):
        for root, dirs, names in os.walk(target):
            dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
            files += [os.path.join(root, f) for f in names if f.endswith(".py")]
    else:
        files = [target]

    grand = 0
    for path in sorted(files):
        hits = scan_file(path)
        if not hits:
            continue
        print(f"\n=== {path} ===")
        seen = set()
        for n, label, advice, line in hits:
            grand += 1
            print(f"  L{n:<5} {label}")
            print(f"         {line.strip()[:100]}")
            if label not in seen:
                print(f"         -> {advice}")
                seen.add(label)

    print(f"\n{grand} thing(s) to look at.")
    if grand == 0:
        print("Nothing SQLite-specific found. The db.py shim should cover you.")


if __name__ == "__main__":
    main()
