-- 001_subscription_and_features.sql
-- Tiers/plans columns on users + new feature tables. Additive and idempotent.
-- (subscription_status and stripe_customer_id already exist from earlier work;
--  the IF NOT EXISTS clauses make those two ALTERs no-ops.)

ALTER TABLE users ADD COLUMN IF NOT EXISTS plan                   TEXT NOT NULL DEFAULT 'free';   -- free | pro
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan_interval          TEXT;                            -- month | year
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status    TEXT;                            -- Stripe status verbatim
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id     TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_period_end     TIMESTAMPTZ;                     -- access expiry
ALTER TABLE users ADD COLUMN IF NOT EXISTS grandfathered          BOOLEAN NOT NULL DEFAULT false;  -- legacy pricing
ALTER TABLE users ADD COLUMN IF NOT EXISTS parent_email           TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS parent_report_optin    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS share_percentile_optin BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_date              DATE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_stripe_customer
    ON users (stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_stripe_subscription
    ON users (stripe_subscription_id) WHERE stripe_subscription_id IS NOT NULL;

-- Backfill: the ADD COLUMN default already makes everyone 'free'. Anyone with an
-- active subscription becomes grandfathered pro (legacy pricing / permanent
-- access). Right now that is the founder's account only. Idempotent via plan check.
UPDATE users
   SET plan = 'pro', grandfathered = true
 WHERE subscription_status = 'active' AND plan <> 'pro';

-- Phase 6: spaced repetition
CREATE TABLE IF NOT EXISTS revision_queue (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_type       TEXT NOT NULL,          -- 'attempt' | 'bank'
    source_id         BIGINT NOT NULL,
    topic             TEXT,
    ease              REAL NOT NULL DEFAULT 2.5,
    interval_days     INTEGER NOT NULL DEFAULT 1,
    repetitions       INTEGER NOT NULL DEFAULT 0,
    due_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_reviewed_at  TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, source_type, source_id)
);
CREATE INDEX IF NOT EXISTS idx_queue_due ON revision_queue (user_id, due_at);

-- Phase 3: cached predictions, recomputed on new marks
CREATE TABLE IF NOT EXISTS grade_predictions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    board             TEXT NOT NULL,
    subject           TEXT NOT NULL,
    grade_score       REAL NOT NULL,
    predicted_grade   TEXT NOT NULL,
    next_grade        TEXT,
    marks_to_next     REAL,
    confidence        TEXT NOT NULL,          -- low | medium | high
    sample_size       INTEGER NOT NULL,
    computed_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, board, subject)
);

-- Phase 9: share cards
CREATE TABLE IF NOT EXISTS share_cards (
    token       TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_type   TEXT NOT NULL,
    payload     JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
