-- Password reset tokens.
--
-- Only a HASH of the token is stored: if the database leaks, the rows are
-- useless for taking over an account. The raw token exists only in the
-- emailed link.
--
-- Single use (used_at) and short lived (expires_at), because a reset link is
-- a bearer credential for the account.

CREATE TABLE IF NOT EXISTS password_resets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    requested_ip TEXT
);

CREATE INDEX IF NOT EXISTS idx_password_resets_user ON password_resets (user_id);
CREATE INDEX IF NOT EXISTS idx_password_resets_expires ON password_resets (expires_at);
