-- Server-side conversion analytics. No third-party tracker.
--
-- Without this you cannot answer the only question that matters about
-- pricing: which feature is actually selling. `detail` carries the feature
-- slug for upgrade prompts and the interval for checkouts.

CREATE TABLE IF NOT EXISTS analytics_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event      TEXT        NOT NULL,
    user_id    BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    detail     TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analytics_event ON analytics_events (event, created_at);
