-- Trend deltas for the redesigned dashboard stat row.
--
-- The UI overhaul brief asks each headline stat to carry a weekly change
-- (+2 papers, +34 questions, up 4% accuracy, up one grade). Three of those
-- four were not computable:
--
--   * question_marks had no timestamp at all, so "questions answered this
--     week" and any accuracy-over-time figure were impossible.
--   * grade_predictions is upserted in place by recompute_predictions(), so
--     the previous prediction was overwritten every time and there was
--     nothing to diff a grade against.
--
-- Neither is backfillable. Deltas only start reading true once a week of new
-- data has accumulated after this ships; until then the dashboard shows the
-- stat without a delta rather than inventing one.
--
-- Safe on the current data: question_marks is empty in production, so the
-- DEFAULT NOW() backfill touches no rows. On a machine with existing rows it
-- would stamp them all with the migration time, which is why the dashboard
-- treats "created_at older than the account" as unknown rather than as real.

ALTER TABLE question_marks
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_question_marks_created
    ON question_marks (created_at);

-- Append-only snapshots of each recomputed prediction. One row per genuine
-- change, not per recompute — recompute_predictions() fires on every mark
-- save, and storing an identical row each time would bury the real movements.
CREATE TABLE IF NOT EXISTS grade_prediction_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    board           TEXT        NOT NULL,
    subject         TEXT        NOT NULL,
    grade_score     REAL        NOT NULL,
    predicted_grade TEXT        NOT NULL,
    confidence      TEXT,
    sample_size     INTEGER     NOT NULL,
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pred_history_lookup
    ON grade_prediction_history (user_id, board, subject, recorded_at DESC);
