-- 012_user_subjects.sql
-- What each student actually studies.
--
-- Until now Telos inferred a student's subjects from the papers they had
-- already logged, which means a new account knows nothing about them until
-- they have done the work — the dashboard, the paper form and the heatmap all
-- open empty and unfiltered. This table records the choice directly, so the
-- app can be about their subjects from the first screen.
--
-- level is stored alongside board and subject because the same subject at the
-- same board is a different qualification at A-Level and AS-Level: different
-- papers, different codes, different boundaries. Today every qualification in
-- paper_templates.py is A-Level, so every row will say so; the column exists
-- because the moment AS or Higher is added, a row without it is ambiguous.
--
-- Existing accounts are backfilled from the papers they have already logged,
-- so nobody who has been using Telos gets asked to introduce themselves again.
--
-- Additive and idempotent.

CREATE TABLE IF NOT EXISTS user_subjects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    board      TEXT        NOT NULL,
    subject    TEXT        NOT NULL,
    level      TEXT        NOT NULL DEFAULT 'A-Level',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, board, subject, level)
);

CREATE INDEX IF NOT EXISTS idx_user_subjects_user
    ON user_subjects (user_id, subject);

-- Backfill from logged papers. ON CONFLICT keeps this safe to re-run.
INSERT INTO user_subjects (user_id, board, subject, level)
SELECT DISTINCT p.user_id, p.board, p.subject, 'A-Level'
  FROM papers p
 WHERE p.board IS NOT NULL AND p.board <> ''
   AND p.subject IS NOT NULL AND p.subject <> ''
ON CONFLICT DO NOTHING;
