-- 016_user_papers.sql
-- Which optional papers a student actually sits.
--
-- Several qualifications are larger than any one student's timetable. Edexcel
-- Further Maths has ten papers and a student sits four; OCR Further Maths has
-- six and a student sits four. Offering all of them to everyone means a
-- Decision student scrolling past Further Mechanics forever, and it gets worse
-- as the catalogue grows.
--
-- Compulsory papers are not stored. They are compulsory — the catalogue already
-- knows which they are, and writing them down here would mean two sources of
-- truth that can disagree. Only a student's optional choices live in this table.
--
-- No backfill, deliberately. An empty selection is read as "show me
-- everything", so existing accounts keep seeing exactly what they saw until
-- they choose otherwise. Guessing someone's option modules from their logged
-- papers would be wrong for anyone who has logged nothing yet.
--
-- Additive and idempotent.

CREATE TABLE IF NOT EXISTS user_papers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    board      TEXT        NOT NULL,
    subject    TEXT        NOT NULL,
    level      TEXT        NOT NULL DEFAULT 'A-Level',
    paper_code TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, board, subject, level, paper_code)
);

CREATE INDEX IF NOT EXISTS idx_user_papers_user
    ON user_papers (user_id, subject);
